spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/maple?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        autoReconnect: true
        enable_lazy_load_no_trans: true
logging:
  level:
    root: error
    im.cave.ms: debug
    org.hibernate: error
